/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalitycsRouteImport } from './routes/analitycs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallBackRouteImport } from './routes/oauth/callBack'

const AnalitycsRoute = AnalitycsRouteImport.update({
  id: '/analitycs',
  path: '/analitycs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallBackRoute = OauthCallBackRouteImport.update({
  id: '/oauth/callBack',
  path: '/oauth/callBack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitycs': typeof AnalitycsRoute
  '/oauth/callBack': typeof OauthCallBackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitycs': typeof AnalitycsRoute
  '/oauth/callBack': typeof OauthCallBackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitycs': typeof AnalitycsRoute
  '/oauth/callBack': typeof OauthCallBackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analitycs' | '/oauth/callBack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analitycs' | '/oauth/callBack'
  id: '__root__' | '/' | '/analitycs' | '/oauth/callBack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitycsRoute: typeof AnalitycsRoute
  OauthCallBackRoute: typeof OauthCallBackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analitycs': {
      id: '/analitycs'
      path: '/analitycs'
      fullPath: '/analitycs'
      preLoaderRoute: typeof AnalitycsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callBack': {
      id: '/oauth/callBack'
      path: '/oauth/callBack'
      fullPath: '/oauth/callBack'
      preLoaderRoute: typeof OauthCallBackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitycsRoute: AnalitycsRoute,
  OauthCallBackRoute: OauthCallBackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
